SET(FILES_H
	${CMAKE_CURRENT_SOURCE_DIR}/formathelper.h
)
# SET(FILES_HPP
# ${CMAKE_CURRENT_SOURCE_DIR}/ezETAProgressBar.hpp)
SET(FILES_CPP
	${CMAKE_CURRENT_SOURCE_DIR}/formathelper.cpp
)

qt_wrap_cpp(FILES_MOC ${FILES_H})

ADD_LIBRARY(pfsadditions STATIC ${FILES_H} ${FILES_HPP} ${FILES_CPP} ${FILES_MOC})
TARGET_LINK_LIBRARIES(pfsadditions Qt6::Core Qt6::Gui Qt6::Widgets)

SET(LUMINANCE_MODULES_GUI ${LUMINANCE_MODULES_GUI} pfsadditions PARENT_SCOPE)
SET(LUMINANCE_MODULES_CLI ${LUMINANCE_MODULES_CLI} pfsadditions PARENT_SCOPE)






