SET(LHDR_NAME "Luminance HDR")

# Numeric version values
SET(LHDR_VERSION_MAJOR "2")
SET(LHDR_VERSION_MINOR "5")
SET(LHDR_VERSION_PATCH "2")
SET(LHDR_VERSION_STR_SUFFIX "-SNAPSHOT")

SET(LHDR_VERSION "${LHDR_VERSION_MAJOR}.${LHDR_VERSION_MINOR}.${LHDR_VERSION_PATCH}${LHDR_VERSION_STR_SUFFIX}")
SET(LHDR_VENDOR "Luminance HDR Development Team")
SET(LHDR_COPYRIGHT_YEAR "2006-2018")

SET(LHDR_OSX_EXECUTABLE_NAME "${LHDR_NAME} ${LHDR_VERSION}")
SET(LHDR_OSX_EXECUTABLE_TARGET "Luminance_HDR_${LHDR_VERSION}")

SET(LHDR_DOMAIN_FIRST "luminance-hdr")
SET(LHDR_DOMAIN_SECOND "com")
SET(LHDR_DOMAIN "${LHDR_DOMAIN_FIRST}.${LHDR_DOMAIN_SECOND}")
