SET(FILES_UI
${CMAKE_CURRENT_SOURCE_DIR}/PreferencesDialog.ui)
SET(FILES_H
${CMAKE_CURRENT_SOURCE_DIR}/PreferencesDialog.h)
SET(FILES_CPP
${CMAKE_CURRENT_SOURCE_DIR}/PreferencesDialog.cpp)

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})

qt_wrap_cpp(FILES_MOC ${FILES_H})
qt_wrap_ui(FILES_UI_H ${FILES_UI})

ADD_LIBRARY(preferencesdialog STATIC ${FILES_H} ${FILES_CPP} ${FILES_MOC} ${FILES_UI_H})
TARGET_LINK_LIBRARIES(preferencesdialog Qt6::Core Qt6::Gui Qt6::Widgets)

SET(FILES_TO_TRANSLATE ${FILES_TO_TRANSLATE} ${FILES_CPP} ${FILES_H} ${FILES_UI} PARENT_SCOPE)
SET(LUMINANCE_MODULES_GUI ${LUMINANCE_MODULES_GUI} preferencesdialog PARENT_SCOPE)
