FIND_PATH(LCMS_INCLUDE_DIR lcms.h
  /usr/local/include
  /usr/include
  /opt/local/include
)

SET(LCMS_NAMES ${LCMS_NAMES} lcms)
FIND_LIBRARY(LCMS_LIBRARY NAMES ${LCMS_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set LCMS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LCMS  DEFAULT_MSG  LCMS_LIBRARY  LCMS_INCLUDE_DIR)

IF(LCMS_FOUND)
  SET( LCMS_LIBRARIES ${LCMS_LIBRARY} )
  IF(NOT LCMS_FIND_QUIETLY)
    MESSAGE(STATUS "Found lcms (LCMS_LIBRARIES = ${LCMS_LIBRARIES})")
    MESSAGE(STATUS "Found lcms (LCMS_INCLUDE_DIR = ${LCMS_INCLUDE_DIR})")
  ENDIF(NOT LCMS_FIND_QUIETLY)
ELSE(LCMS_FOUND)
  IF(LCMS_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find lcms")
  ENDIF(LCMS_FIND_REQUIRED)
ENDIF(LCMS_FOUND)



MARK_AS_ADVANCED(LCMS_INCLUDE_DIR LCMS_LIBRARY)

